name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 532549085896.dkr.ecr.ap-south-1.amazonaws.com
  ECR_REPOSITORY: incident-responder

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Run linter
        run: ruff check . --fix
      - name: Run tests
        run: |
          export PYTHONPATH=${{ github.workspace }}
          pytest tests/ -v

  build-push:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      image-tag: ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Set image tag
        id: meta
        run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
      - name: Build Docker image
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} .
          docker tag ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL
      - name: Push image to ECR
        run: |
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest

  update-gitops:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - uses: actions/checkout@v4
        with:
          repository: GY2AN/devops-gitops
          token: ${{ secrets.GITOPS_PAT }}
      - name: Update image tag
        run: |
          sed -i "s|tag:.*|tag: ${{ github.sha }}|" charts/incident-responder/values.yaml
          git config user.email "ci-bot@github.com"
          git config user.name "CI Bot"
          git add charts/incident-responder/values.yaml
          git diff --staged --quiet || git commit -m "ci: update incident-responder image tag to ${{ github.sha }}"
          git push

